### ISSUE TITLE
unknown symbol "PyInt_AsSsize_t" (Fiddle::DLError)

### ISSUE THREAD

**Issue by kou** [mrkn/pycall.rb#101]
```console
$ PYCALL_DEBUG_FIND_LIBPYTHON=1 PATH=/tmp/local/bin:$PATH ruby -ve 'require "matplotlib"
ruby 2.7.0dev (2019-09-29T17:56:15Z master 54d49aeb52) [x86_64-linux]
DEBUG(find_libpython) find_libpython(nil)
DEBUG(find_libpython) investigate_python_config("python3")
DEBUG(find_libpython) libs: ["libpython3.7m.so.1.0", "libpython3.7m.so", "libpython3.7m", "libpython3.7", "libpython"]
DEBUG(find_libpython) libpaths: ["/usr/lib", "/lib", "", "/usr", "/usr/lib"]
DEBUG(find_libpython) Unable to find /usr/lib/libpython3.7m.so.1.0
DEBUG(find_libpython) Unable to find /usr/lib/libpython3.7m.so.1.0.so
DEBUG(find_libpython) dlopen("/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0") = #<Fiddle::Handle:0x0000563b910297e8>
Traceback (most recent call last):
	2: from -e:1:in `<main>'
	1: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require': cannot load such file -- matplotlib (LoadError)
	9: from -e:1:in `<main>'
	8: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	7: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `rescue in require'
	6: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `require'
	5: from /tmp/local/lib/ruby/gems/2.7.0/gems/matplotlib-1.0.0/lib/matplotlib.rb:4:in `<top (required)>'
	4: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall.rb:62:in `import_module'
	3: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall/init.rb:16:in `const_missing'
	2: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall/init.rb:43:in `init'
	1: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require'
/tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:81:in `require': cannot load such file -- 2.7/pycall.so (LoadError)
	11: from -e:1:in `<main>'
	10: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 9: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `rescue in require'
	 8: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:157:in `require'
	 7: from /tmp/local/lib/ruby/gems/2.7.0/gems/matplotlib-1.0.0/lib/matplotlib.rb:4:in `<top (required)>'
	 6: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall.rb:62:in `import_module'
	 5: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall/init.rb:16:in `const_missing'
	 4: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall/init.rb:41:in `init'
	 3: from /tmp/local/lib/ruby/gems/2.7.0/gems/pycall-1.3.0.dev/lib/pycall/init.rb:45:in `rescue in init'
	 2: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:61:in `require'
	 1: from /tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:61:in `require'
/tmp/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:61:in `sym': unknown symbol "PyInt_AsSsize_t" (Fiddle::DLError)
```

It seems that `PyInt_AsSsize_t` exists only in Python 2: https://docs.python.org/2/c-api/int.html#c.PyInt_AsSsize_t
Python 3 provides `PyLong_AsSsize_t`: https://docs.python.org/3/c-api/long.html#c.PyLong_AsSsize_t

**Comment by mrkn** [comment]
Thanks for the report.

It seems that the version checking may fail.

I tried to reproduce on my Ubuntu bionic machine, but I couldn't, unfortunately.

```
mrkn@mrkn-devel:~$ python3.7 -m pip install pillow
Collecting pillow
  Downloading
    100% |████████████████████████████████| 2.1MB 965kB/s
Installing collected packages: pillow
Successfully installed pillow-6.2.0
mrkn@mrkn-devel:~$ PYCALL_DEBUG_FIND_LIBPYTHON=1 irb -rpycall
irb(main):001:0> PyCall.init("python3.7")
DEBUG(find_libpython) find_libpython("python3.7")
DEBUG(find_libpython) investigate_python_config("python3.7")
DEBUG(find_libpython) libs: ["libpython3.7m.so.1.0", "libpython3.7m.so", "libpython3.7m", "libpython3.7", "libpython"]
DEBUG(find_libpython) libpaths: ["/usr/lib", "/usr/lib", "", "/usr", "/usr/lib"]
DEBUG(find_libpython) Unable to find /usr/lib/libpython3.7m.so.1.0
DEBUG(find_libpython) Unable to find /usr/lib/libpython3.7m.so.1.0.so
DEBUG(find_libpython) dlopen("/usr/lib/x86_64-linux-gnu/libpython3.7m.so.1.0") = #<Fiddle::Handle:0x0000560618af6238>
=> true
irb(main):002:0> require "matplotlib"
=> true
```

**Comment by kou** [comment]
What information should I provide?
Or should I create a pull request?

**Comment by mrkn** [comment]
It is great for me if you can create a pull-request by yourself.

`PyInt_AsSsize_t` is refered at [this line](https://github.com/mrkn/pycall.rb/blob/master/ext/pycall/libpython.c#L139), but it's referred as an optional symbol, so it should not raise an error.

What version of fiddle do you use?

**Comment by kou** [comment]
I use Fiddle bundled in `ruby 2.7.0dev (2019-09-29T17:56:15Z master 54d49aeb52) [x86_64-linux]`.

**Comment by mrkn** [comment]
OK.

I suspect that the error occurred in `fiddle_handle_sym` function that is called via `rb_funcall` at [here](https://github.com/mrkn/pycall.rb/blob/master/ext/pycall/libpython.c#L20).  If so, `rb_protect` at [here](https://github.com/mrkn/pycall.rb/blob/master/ext/pycall/libpython.c#L32) fails to protect the error but I have no idea the cause of that.

Could you investigate whether my guess is correct?

**Comment by kou** [comment]
I've created pull request: #102
