### ISSUE TITLE
Force deallocation of Python object

### ISSUE THREAD

**Issue by kammerer** [mrkn/pycall.rb#71]
Is it possible to somehow ensure that Python object was removed from memory? I am trying to use PyCall to use GDAL with Ruby. The only way to ensure that a raster was actually written to disk is to deallocate it.

**Comment by mrkn** [comment]
@kammerer I understand the inconvenience that a Python object referred from Ruby isn't freed when leaving the scope.  The reason is Ruby's mark-and-sweep GC.

Currently, you can use `PyCall::PyPtr.decref` class method for this case.  Let `pyobj` is a `PyCall::PyObjectWrapper` object you want to force deallocate, you can do it by:

```ruby
PyCall::PyPtr.decref(pyobj.__pyptr__)
```

After calling `PyCall::PyPtr.decref` for the `PyCall::PyPtr` object that has refcnt==2, the address the `PyCall::PyPtr` object indicates changes to `0` (NULL).

```
[1] pry(main)> po = PyCall.eval('object()')
=> <object object at 0x10ec4b110>
[2] pry(main)> po.__pyptr__.__ob_refcnt__
=> 2
[3] pry(main)> PyCall::PyPtr.decref(po.__pyptr__)
=> #<PyCall::PyPtr:0x3fc2eb0a7ab0>
[4] pry(main)> po.__pyptr__.__ob_refcnt__
=> nil
[5] pry(main)> po.__pyptr__.__address__
=> 0
[6] pry(main)>
```

**Comment by svilenkov** [comment]
Hey @mrkn 

When I run your command in IRB console that uses ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

I get the following segmentation fault
```
root@97b43330976b:/app# irb
irb(main):001:0> require 'pycall'
=> true
irb(main):002:0> PyCall::PyPtr.decref(PyCall.eval('object()').__pyptr__)
/usr/local/lib/ruby/2.4.0/irb/inspector.rb:109: [BUG] Segmentation fault at 0x00000000000008
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0020 p:---- s:0092 e:000091 CFUNC  :inspect
c:0019 p:0011 s:0088 e:000087 BLOCK  /usr/local/lib/ruby/2.4.0/irb/inspector.rb:109 [FINISH]
c:0018 p:0012 s:0084 e:000083 METHOD /usr/local/lib/ruby/2.4.0/irb/inspector.rb:102
c:0017 p:0013 s:0079 e:000078 METHOD /usr/local/lib/ruby/2.4.0/irb/context.rb:385
c:0016 p:0017 s:0075 e:000072 METHOD /usr/local/lib/ruby/2.4.0/irb.rb:665
c:0015 p:0039 s:0069 e:000068 BLOCK  /usr/local/lib/ruby/2.4.0/irb.rb:494
c:0014 p:0041 s:0060 e:000059 METHOD /usr/local/lib/ruby/2.4.0/irb.rb:627
c:0013 p:0011 s:0054 e:000053 BLOCK  /usr/local/lib/ruby/2.4.0/irb.rb:490
c:0012 p:0128 s:0049 e:000048 BLOCK  /usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:246 [FINISH]
c:0011 p:---- s:0045 e:000044 CFUNC  :loop
c:0010 p:0009 s:0041 e:000040 BLOCK  /usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232 [FINISH]
c:0009 p:---- s:0038 e:000037 CFUNC  :catch
c:0008 p:0018 s:0033 e:000032 METHOD /usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231
c:0007 p:0037 s:0029 E:000d00 METHOD /usr/local/lib/ruby/2.4.0/irb.rb:489
c:0006 p:0008 s:0025 e:000024 BLOCK  /usr/local/lib/ruby/2.4.0/irb.rb:430 [FINISH]
c:0005 p:---- s:0022 e:000021 CFUNC  :catch
c:0004 p:0075 s:0017 E:000888 METHOD /usr/local/lib/ruby/2.4.0/irb.rb:429
c:0003 p:0118 s:0012 e:000011 METHOD /usr/local/lib/ruby/2.4.0/irb.rb:385
c:0002 p:0023 s:0006 e:000005 EVAL   /usr/local/bin/irb:11 [FINISH]
c:0001 p:0000 s:0003 E:001cf0 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/usr/local/bin/irb:11:in `<main>'
/usr/local/lib/ruby/2.4.0/irb.rb:385:in `start'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `run'
/usr/local/lib/ruby/2.4.0/irb.rb:429:in `catch'
/usr/local/lib/ruby/2.4.0/irb.rb:430:in `block in run'
/usr/local/lib/ruby/2.4.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.4.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:627:in `signal_status'
/usr/local/lib/ruby/2.4.0/irb.rb:494:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.4.0/irb.rb:665:in `output_value'
/usr/local/lib/ruby/2.4.0/irb/context.rb:385:in `inspect_last_value'
/usr/local/lib/ruby/2.4.0/irb/inspector.rb:102:in `inspect_value'
/usr/local/lib/ruby/2.4.0/irb/inspector.rb:109:in `block in <module:IRB>'
/usr/local/lib/ruby/2.4.0/irb/inspector.rb:109:in `inspect'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f3723ee61bf RBP: 0x0000000000000000 RSP: 0x00007ffe31f74340
 RAX: 0x0000000002158388 RBX: 0x0000000002158680 RCX: 0x000000000217af50
 RDX: 0x0000007274507950 RDI: 0x0000000001c0fe30 RSI: 0x0000000000000005
  R8: 0x00007f372707e2f0  R9: 0x0000000001bafac0 R10: 0x00007ffe31f74100
 R11: 0x00007f3726c57480 R12: 0x0000000002158680 R13: 0x0000000000000000
 R14: 0x0000000001fb1950 R15: 0x0000000002158680 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/usr/local/lib/libruby.so.2.4(rb_vm_bugreport+0x4f3) [0x7f3726c7e683] vm_dump.c:684
/usr/local/lib/libruby.so.2.4(rb_bug_context+0xd4) [0x7f3726afd3a4] error.c:506
/usr/local/lib/libruby.so.2.4(sigsegv+0x3e) [0x7f3726bf205e] signal.c:907
/lib/x86_64-linux-gnu/libpthread.so.0 [0x7f3726849890]
/usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so(pycall_pyptr_inspect+0x5f) [0x7f3723ee61bf] pycall.c:358
/usr/local/lib/libruby.so.2.4(vm_call_cfunc+0xef) [0x7f3726c60f3f] vm_insnhelper.c:1752
/usr/local/lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f3726c72b13] vm_insnhelper.c:2292
/usr/local/lib/libruby.so.2.4(vm_exec_core+0x1610) [0x7f3726c6a3d0] insns.def:1066
/usr/local/lib/libruby.so.2.4(vm_exec+0x8b) [0x7f3726c6f42b] vm.c:1727
/usr/local/lib/libruby.so.2.4(invoke_iseq_block_from_c+0x516) [0x7f3726c70206] vm.c:969
/usr/local/lib/libruby.so.2.4(invoke_block_from_c_unsplattable+0xe0) [0x7f3726c70410] vm.c:1101
/usr/local/lib/libruby.so.2.4(vm_invoke_proc+0xd3) [0x7f3726c70583] vm.c:1126
/usr/local/lib/libruby.so.2.4(vm_call_opt_call+0xa9) [0x7f3726c722a9] vm_insnhelper.c:1979
/usr/local/lib/libruby.so.2.4(vm_exec_core+0x1610) [0x7f3726c6a3d0] insns.def:1066
/usr/local/lib/libruby.so.2.4(vm_exec+0x8b) [0x7f3726c6f42b] vm.c:1727
/usr/local/lib/libruby.so.2.4(invoke_iseq_block_from_c+0x516) [0x7f3726c70206] vm.c:969
/usr/local/lib/libruby.so.2.4(loop_i+0xd0) [0x7f3726c710a0] vm.c:1032
/usr/local/lib/libruby.so.2.4(rb_rescue2+0xc7) [0x7f3726b05e17] eval.c:838
/usr/local/lib/libruby.so.2.4(vm_call_cfunc+0xef) [0x7f3726c60f3f] vm_insnhelper.c:1752
/usr/local/lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f3726c72b13] vm_insnhelper.c:2292
/usr/local/lib/libruby.so.2.4(vm_exec_core+0x113f) [0x7f3726c69eff] insns.def:967
/usr/local/lib/libruby.so.2.4(vm_exec+0x8b) [0x7f3726c6f42b] vm.c:1727
/usr/local/lib/libruby.so.2.4(invoke_iseq_block_from_c+0x516) [0x7f3726c70206] vm.c:969
/usr/local/lib/libruby.so.2.4(catch_i+0xb4) [0x7f3726c70cc4] vm.c:1032
/usr/local/lib/libruby.so.2.4(vm_catch_protect+0x9c) [0x7f3726c632cc] vm_eval.c:2043
/usr/local/lib/libruby.so.2.4(rb_catch_obj+0x19) [0x7f3726c63399] vm_eval.c:2017
/usr/local/lib/libruby.so.2.4(vm_call_cfunc+0xef) [0x7f3726c60f3f] vm_insnhelper.c:1752
/usr/local/lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f3726c72b13] vm_insnhelper.c:2292
/usr/local/lib/libruby.so.2.4(vm_exec_core+0x113f) [0x7f3726c69eff] insns.def:967
/usr/local/lib/libruby.so.2.4(vm_exec+0x8b) [0x7f3726c6f42b] vm.c:1727
/usr/local/lib/libruby.so.2.4(invoke_iseq_block_from_c+0x516) [0x7f3726c70206] vm.c:969
/usr/local/lib/libruby.so.2.4(catch_i+0xb4) [0x7f3726c70cc4] vm.c:1032
/usr/local/lib/libruby.so.2.4(vm_catch_protect+0x9c) [0x7f3726c632cc] vm_eval.c:2043
/usr/local/lib/libruby.so.2.4(rb_catch_obj+0x19) [0x7f3726c63399] vm_eval.c:2017
/usr/local/lib/libruby.so.2.4(vm_call_cfunc+0xef) [0x7f3726c60f3f] vm_insnhelper.c:1752
/usr/local/lib/libruby.so.2.4(vm_call_method+0xe3) [0x7f3726c72b13] vm_insnhelper.c:2292
/usr/local/lib/libruby.so.2.4(vm_exec_core+0x113f) [0x7f3726c69eff] insns.def:967
/usr/local/lib/libruby.so.2.4(vm_exec+0x8b) [0x7f3726c6f42b] vm.c:1727
/usr/local/lib/libruby.so.2.4(ruby_exec_internal+0xb2) [0x7f3726b03132] eval.c:244
/usr/local/lib/libruby.so.2.4(ruby_exec_node+0x1d) [0x7f3726b04ead] eval.c:308
/usr/local/lib/libruby.so.2.4(ruby_run_node+0x1e) [0x7f3726b07a6e] eval.c:300
/usr/local/bin/ruby(main+0x4b) [0x40087b] main.c:36

-- Other runtime information -----------------------------------------------

* Loaded script: irb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
    5 /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
    6 /usr/local/lib/ruby/2.4.0/unicode_normalize.rb
    7 /usr/local/lib/ruby/2.4.0/x86_64-linux/rbconfig.rb
    8 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/compatibility.rb
    9 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/defaults.rb
   10 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/deprecate.rb
   11 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/errors.rb
   12 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/version.rb
   13 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/requirement.rb
   14 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/platform.rb
   15 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/basic_specification.rb
   16 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/stub_specification.rb
   17 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/util/list.rb
   18 /usr/local/lib/ruby/2.4.0/x86_64-linux/stringio.so
   19 /usr/local/lib/ruby/2.4.0/uri/rfc2396_parser.rb
   20 /usr/local/lib/ruby/2.4.0/uri/rfc3986_parser.rb
   21 /usr/local/lib/ruby/2.4.0/uri/common.rb
   22 /usr/local/lib/ruby/2.4.0/uri/generic.rb
   23 /usr/local/lib/ruby/2.4.0/uri/ftp.rb
   24 /usr/local/lib/ruby/2.4.0/uri/http.rb
   25 /usr/local/lib/ruby/2.4.0/uri/https.rb
   26 /usr/local/lib/ruby/2.4.0/uri/ldap.rb
   27 /usr/local/lib/ruby/2.4.0/uri/ldaps.rb
   28 /usr/local/lib/ruby/2.4.0/uri/mailto.rb
   29 /usr/local/lib/ruby/2.4.0/uri.rb
   30 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb
   31 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/exceptions.rb
   32 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/util.rb
   33 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/bundler_version_finder.rb
   34 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb
   35 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_gem.rb
   36 /usr/local/lib/ruby/2.4.0/monitor.rb
   37 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb
   38 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems.rb
   39 /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/path_support.rb
   40 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/version.rb
   41 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/core_ext/name_error.rb
   42 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/levenshtein.rb
   43 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/jaro_winkler.rb
   44 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checker.rb
   45 /usr/local/lib/ruby/2.4.0/delegate.rb
   46 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   47 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   48 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   49 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   50 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/spell_checkers/null_checker.rb
   51 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
   52 /usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
   53 /usr/local/lib/ruby/2.4.0/e2mmap.rb
   54 /usr/local/lib/ruby/2.4.0/irb/init.rb
   55 /usr/local/lib/ruby/2.4.0/irb/workspace.rb
   56 /usr/local/lib/ruby/2.4.0/irb/inspector.rb
   57 /usr/local/lib/ruby/2.4.0/irb/output-method.rb
   58 /usr/local/lib/ruby/2.4.0/irb/context.rb
   59 /usr/local/lib/ruby/2.4.0/irb/extend-command.rb
   60 /usr/local/lib/ruby/2.4.0/irb/notifier.rb
   61 /usr/local/lib/ruby/2.4.0/irb/slex.rb
   62 /usr/local/lib/ruby/2.4.0/irb/ruby-token.rb
   63 /usr/local/lib/ruby/2.4.0/irb/ruby-lex.rb
   64 /usr/local/lib/ruby/2.4.0/irb/src_encoding.rb
   65 /usr/local/lib/ruby/2.4.0/irb/magic-file.rb
   66 /usr/local/lib/ruby/2.4.0/x86_64-linux/readline.so
   67 /usr/local/lib/ruby/2.4.0/irb/input-method.rb
   68 /usr/local/lib/ruby/2.4.0/irb/locale.rb
   69 /usr/local/lib/ruby/2.4.0/irb.rb
   70 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/version.rb
   71 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/error.rb
   72 /usr/local/lib/ruby/2.4.0/x86_64-linux/fiddle.so
   73 /usr/local/lib/ruby/2.4.0/fiddle/function.rb
   74 /usr/local/lib/ruby/2.4.0/fiddle/closure.rb
   75 /usr/local/lib/ruby/2.4.0/fiddle.rb
   76 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/libpython/finder.rb
   77 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/libpython.rb
   78 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/pyerror.rb
   79 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/wrapper_object_cache.rb
   80 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/pyobject_wrapper.rb
   81 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/pytypeobject_wrapper.rb
   82 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/init.rb
   83 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.rb
   84 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so
   85 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/dict.rb
   86 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/list.rb
   87 /usr/local/bundle/gems/pycall-1.0.3/lib/pycall/slice.rb

* Process memory map:

00400000-00401000 r-xp 00000000 08:01 927867                             /usr/local/bin/ruby
00600000-00601000 rw-p 00000000 08:01 927867                             /usr/local/bin/ruby
01baf000-02250000 rw-p 00000000 00:00 0                                  [heap]
7f3722a61000-7f3722c0a000 r--s 00000000 08:01 664516                     /lib/x86_64-linux-gnu/libc-2.19.so
7f3722c0a000-7f3722c8b000 r--s 00000000 08:01 810737                     /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so
7f3722c8b000-7f3722cad000 r--s 00000000 08:01 664580                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3722cad000-7f3723ba8000 r--s 00000000 08:01 927905                     /usr/local/lib/libruby.so.2.4.1
7f3723ba8000-7f3723bcc000 r--s 00000000 08:01 927867                     /usr/local/bin/ruby
7f3723bcc000-7f3723be2000 r-xp 00000000 08:01 2910637                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3723be2000-7f3723de1000 ---p 00016000 08:01 2910637                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3723de1000-7f3723de2000 rw-p 00015000 08:01 2910637                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f3723ded000-7f3723ede000 rw-p 00000000 00:00 0
7f3723ede000-7f3723eef000 r-xp 00000000 08:01 810737                     /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so
7f3723eef000-7f37240ee000 ---p 00011000 08:01 810737                     /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so
7f37240ee000-7f37240f0000 rw-p 00010000 08:01 810737                     /usr/local/bundle/gems/pycall-1.0.3/lib/pycall.so
7f37240f0000-7f37240f2000 r-xp 00000000 08:01 664606                     /lib/x86_64-linux-gnu/libutil-2.19.so
7f37240f2000-7f37242f1000 ---p 00002000 08:01 664606                     /lib/x86_64-linux-gnu/libutil-2.19.so
7f37242f1000-7f37242f2000 r--p 00001000 08:01 664606                     /lib/x86_64-linux-gnu/libutil-2.19.so
7f37242f2000-7f37242f3000 rw-p 00002000 08:01 664606                     /lib/x86_64-linux-gnu/libutil-2.19.so
7f37242f3000-7f372430d000 r-xp 00000000 08:01 664611                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f372430d000-7f372450c000 ---p 0001a000 08:01 664611                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f372450c000-7f372450d000 r--p 00019000 08:01 664611                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f372450d000-7f372450e000 rw-p 0001a000 08:01 664611                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f372450e000-7f3724802000 r-xp 00000000 08:01 1466974                    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
7f3724802000-7f3724a01000 ---p 002f4000 08:01 1466974                    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
7f3724a01000-7f3724a03000 r--p 002f3000 08:01 1466974                    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
7f3724a03000-7f3724a81000 rw-p 002f5000 08:01 1466974                    /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
7f3724a81000-7f3724a93000 rw-p 00000000 00:00 0
7f3724a93000-7f3724a9a000 r-xp 00000000 08:01 539262                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
7f3724a9a000-7f3724c9a000 ---p 00007000 08:01 539262                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
7f3724c9a000-7f3724c9b000 r--p 00007000 08:01 539262                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
7f3724c9b000-7f3724c9c000 rw-p 00008000 08:01 539262                     /usr/lib/x86_64-linux-gnu/libffi.so.6.0.2
7f3724c9c000-7f3724ca5000 r-xp 00000000 08:01 1318183                    /usr/local/lib/ruby/2.4.0/x86_64-linux/fiddle.so
7f3724ca5000-7f3724ea4000 ---p 00009000 08:01 1318183                    /usr/local/lib/ruby/2.4.0/x86_64-linux/fiddle.so
7f3724ea4000-7f3724ea5000 rw-p 00008000 08:01 1318183                    /usr/local/lib/ruby/2.4.0/x86_64-linux/fiddle.so
7f3724ea5000-7f3724ecb000 r-xp 00000000 08:01 664601                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f3724ecb000-7f37250ca000 ---p 00026000 08:01 664601                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f37250ca000-7f37250ce000 r--p 00025000 08:01 664601                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f37250ce000-7f37250cf000 rw-p 00029000 08:01 664601                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f37250cf000-7f37250f3000 r-xp 00000000 08:01 664552                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f37250f3000-7f37252f2000 ---p 00024000 08:01 664552                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f37252f2000-7f37252f3000 r--p 00023000 08:01 664552                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f37252f3000-7f37252f4000 rw-p 00024000 08:01 664552                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f37252f4000-7f3725334000 r-xp 00000000 08:01 664583                     /lib/x86_64-linux-gnu/libreadline.so.6.3
7f3725334000-7f3725534000 ---p 00040000 08:01 664583                     /lib/x86_64-linux-gnu/libreadline.so.6.3
7f3725534000-7f3725536000 r--p 00040000 08:01 664583                     /lib/x86_64-linux-gnu/libreadline.so.6.3
7f3725536000-7f372553d000 rw-p 00042000 08:01 664583                     /lib/x86_64-linux-gnu/libreadline.so.6.3
7f372553d000-7f372553e000 rw-p 00000000 00:00 0
7f372553e000-7f3725546000 r-xp 00000000 08:01 1318192                    /usr/local/lib/ruby/2.4.0/x86_64-linux/readline.so
7f3725546000-7f3725745000 ---p 00008000 08:01 1318192                    /usr/local/lib/ruby/2.4.0/x86_64-linux/readline.so
7f3725745000-7f3725746000 rw-p 00007000 08:01 1318192                    /usr/local/lib/ruby/2.4.0/x86_64-linux/readline.so
7f3725746000-7f372574e000 r-xp 00000000 08:01 1318196                    /usr/local/lib/ruby/2.4.0/x86_64-linux/stringio.so
7f372574e000-7f372594d000 ---p 00008000 08:01 1318196                    /usr/local/lib/ruby/2.4.0/x86_64-linux/stringio.so
7f372594d000-7f372594e000 rw-p 00007000 08:01 1318196                    /usr/local/lib/ruby/2.4.0/x86_64-linux/stringio.so
7f372594e000-7f3725951000 r-xp 00000000 08:01 1456149                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7f3725951000-7f3725b50000 ---p 00003000 08:01 1456149                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7f3725b50000-7f3725b51000 rw-p 00002000 08:01 1456149                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/trans/transdb.so
7f3725b51000-7f3725b53000 r-xp 00000000 08:01 1456106                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7f3725b53000-7f3725d52000 ---p 00002000 08:01 1456106                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7f3725d52000-7f3725d53000 rw-p 00001000 08:01 1456106                    /usr/local/lib/ruby/2.4.0/x86_64-linux/enc/encdb.so
7f3725d53000-7f3725ef4000 r-xp 00000000 08:01 664516                     /lib/x86_64-linux-gnu/libc-2.19.so
7f3725ef4000-7f37260f4000 ---p 001a1000 08:01 664516                     /lib/x86_64-linux-gnu/libc-2.19.so
7f37260f4000-7f37260f8000 r--p 001a1000 08:01 664516                     /lib/x86_64-linux-gnu/libc-2.19.so
7f37260f8000-7f37260fa000 rw-p 001a5000 08:01 664516                     /lib/x86_64-linux-gnu/libc-2.19.so
7f37260fa000-7f37260fe000 rw-p 00000000 00:00 0
7f37260fe000-7f37261fe000 r-xp 00000000 08:01 664546                     /lib/x86_64-linux-gnu/libm-2.19.so
7f37261fe000-7f37263fd000 ---p 00100000 08:01 664546                     /lib/x86_64-linux-gnu/libm-2.19.so
7f37263fd000-7f37263fe000 r--p 000ff000 08:01 664546                     /lib/x86_64-linux-gnu/libm-2.19.so
7f37263fe000-7f37263ff000 rw-p 00100000 08:01 664546                     /lib/x86_64-linux-gnu/libm-2.19.so
7f37263ff000-7f3726407000 r-xp 00000000 08:01 664524                     /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3726407000-7f3726606000 ---p 00008000 08:01 664524                     /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3726606000-7f3726607000 r--p 00007000 08:01 664524                     /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3726607000-7f3726608000 rw-p 00008000 08:01 664524                     /lib/x86_64-linux-gnu/libcrypt-2.19.so
7f3726608000-7f3726636000 rw-p 00000000 00:00 0
7f3726636000-7f3726639000 r-xp 00000000 08:01 664529                     /lib/x86_64-linux-gnu/libdl-2.19.so
7f3726639000-7f3726838000 ---p 00003000 08:01 664529                     /lib/x86_64-linux-gnu/libdl-2.19.so
7f3726838000-7f3726839000 r--p 00002000 08:01 664529                     /lib/x86_64-linux-gnu/libdl-2.19.so
7f3726839000-7f372683a000 rw-p 00003000 08:01 664529                     /lib/x86_64-linux-gnu/libdl-2.19.so
7f372683a000-7f3726852000 r-xp 00000000 08:01 664580                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3726852000-7f3726a51000 ---p 00018000 08:01 664580                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3726a51000-7f3726a52000 r--p 00017000 08:01 664580                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3726a52000-7f3726a53000 rw-p 00018000 08:01 664580                     /lib/x86_64-linux-gnu/libpthread-2.19.so
7f3726a53000-7f3726a57000 rw-p 00000000 00:00 0
7f3726a57000-7f3726d58000 r-xp 00000000 08:01 927905                     /usr/local/lib/libruby.so.2.4.1
7f3726d58000-7f3726f57000 ---p 00301000 08:01 927905                     /usr/local/lib/libruby.so.2.4.1
7f3726f57000-7f3726f60000 rw-p 00300000 08:01 927905                     /usr/local/lib/libruby.so.2.4.1
7f3726f60000-7f3726f71000 rw-p 00000000 00:00 0
7f3726f71000-7f3726f92000 r-xp 00000000 08:01 664498                     /lib/x86_64-linux-gnu/ld-2.19.so
7f3726f9c000-7f3727184000 rw-p 00000000 00:00 0
7f3727188000-7f372718b000 rw-p 00000000 00:00 0
7f372718b000-7f372718c000 ---p 00000000 00:00 0
7f372718c000-7f3727191000 rw-p 00000000 00:00 0
7f3727191000-7f3727192000 r--p 00020000 08:01 664498                     /lib/x86_64-linux-gnu/ld-2.19.so
7f3727192000-7f3727193000 rw-p 00021000 08:01 664498                     /lib/x86_64-linux-gnu/ld-2.19.so
7f3727193000-7f3727194000 rw-p 00000000 00:00 0
7ffe31779000-7ffe31f78000 rw-p 00000000 00:00 0                          [stack]
7ffe31f93000-7ffe31f95000 r--p 00000000 00:00 0                          [vvar]
7ffe31f95000-7ffe31f97000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted
```

**Comment by mrkn** [comment]
@svilenkov I'll investigate what's going on. Thank you for the report.
