### ISSUE TITLE
PyCall::PythonNotFound on Windows

### ISSUE THREAD

**Issue by juliaps** [mrkn/pycall.rb#86]
When I compile a simple code on Windows get this error :

C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/libpython/finder.rb:34:in `rescue in find_python_config': PyCall::PythonNotFound (PyCall::PythonNotFound)
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/libpython/finder.rb:27:in `find_python_config'
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/libpython/finder.rb:41:in `find_libpython'
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/init.rb:35:in `init'
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/init.rb:16:in `const_missing'
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall.rb:62:in `import_module'
        from C:/COSMOS/Vendor/Ruby/lib/ruby/gems/2.4.0/gems/pycall-1.2.1/lib/pycall/import.rb:18:in `pyimport'
        from teste.rb:5:in `<main>'

I'm using the fuction visa by python. You have any idea for this error?

**Comment by mrkn** [comment]
Please investigate your environment by the instruction described here: https://github.com/mrkn/pycall.rb#debugging-python-finder

**Comment by felixmarch** [comment]
Hi @mrkn Can you please advice how to perform debugging on [https://github.com/mrkn/pycall.rb#debugging-python-finder](https://github.com/mrkn/pycall.rb#debugging-python-finder)?

On Windows prompt, the command "`PYCALL_DEBUG_FIND_LIBPYTHON=1 ruby -rpycall -ePyCall.builtins`" is invalid

I am using python from anaconda windows installer, btw: [https://www.anaconda.com/download/success](https://www.anaconda.com/download/success)

```
(base) C:\Windows\system32>gem install pandas
Fetching pandas-0.3.8.gem
Fetching pycall-1.5.2.gem
Fetching numpy-0.4.0.gem
Building native extensions. This could take a while...
Successfully installed pycall-1.5.2
Successfully installed numpy-0.4.0
Successfully installed pandas-0.3.8
Parsing documentation for pycall-1.5.2
Installing ri documentation for pycall-1.5.2
Parsing documentation for numpy-0.4.0
Installing ri documentation for numpy-0.4.0
Parsing documentation for pandas-0.3.8
Installing ri documentation for pandas-0.3.8
Done installing documentation for pycall, numpy, pandas after 1 seconds
3 gems installed

(base) C:\Windows\system32>irb
irb(main):001:0> require 'pandas'
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:127:in `+': no implicit conversion of nil into String (TypeError)
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:127:in `normalize_path'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:55:in `block in find_libpython'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:109:in `block (2 levels) in candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:108:in `each'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:108:in `block in candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:107:in `each'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:107:in `candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:53:in `find_libpython'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/init.rb:33:in `init'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/init.rb:16:in `const_missing'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall.rb:82:in `import_module'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/numpy-0.4.0/lib/numpy.rb:4:in `<top (required)>'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pandas-0.3.8/lib/pandas.rb:2:in `<top (required)>'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        ... 6 levels...
<internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- pandas (LoadError)
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from (irb):1:in `<main>'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
        from C:/Ruby/bin/irb:33:in `load'
        from C:/Ruby/bin/irb:33:in `<main>'
irb(main):002:0>
irb(main):002:0>

(base) C:\Windows\system32>PYCALL_DEBUG_FIND_LIBPYTHON=1 ruby -rpycall -ePyCall.builtins
'PYCALL_DEBUG_FIND_LIBPYTHON' is not recognized as an internal or external command,
operable program or batch file.

(base) C:\Windows\system32>
```

**Comment by felixmarch** [comment]
It seems I found the source of the problem, the windows doesn't work with slash and need backslash to access `"C:\ProgramData\anaconda3\python311.dll"`

Can you please advice how to handle this issue?

```
(base) C:\Windows\system32>set PYCALL_DEBUG_FIND_LIBPYTHON=1

(base) C:\Windows\system32>ruby -rpycall -ePyCall.builtins
DEBUG(find_libpython) find_libpython(nil)
DEBUG(find_libpython) investigate_python_config("python3")
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
DEBUG(find_libpython) investigate_python_config("python")
DEBUG(find_libpython) Candidate: C:\ProgramData\anaconda3\python311.dll
DEBUG(find_libpython) Trying to dlopen: C:/ProgramData/anaconda3/python311.dll
DEBUG(find_libpython) dlopen("C:/ProgramData/anaconda3/python311.dll") => Fiddle::DLError: No such file or directory
DEBUG(find_libpython) libpaths: ["C:\\ProgramData\\anaconda3", "C:\\ProgramData\\anaconda3/lib"]
DEBUG(find_libpython) candidate_names: ["python3.11", "python"]
DEBUG(find_libpython) Candidate: C:\ProgramData\anaconda3/python3.11
C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:127:in `+': no implicit conversion of nil into String (TypeError)
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:127:in `normalize_path'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:55:in `block in find_libpython'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:109:in `block (2 levels) in candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:108:in `each'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:108:in `block in candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:107:in `each'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:107:in `candidate_paths'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/libpython/finder.rb:53:in `find_libpython'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/init.rb:33:in `init'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall/init.rb:16:in `const_missing'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/pycall-1.5.2/lib/pycall.rb:14:in `builtins'
        from -e:1:in `<main>'


(base) C:\Windows\system32>dir "C:\ProgramData\anaconda3\python311.dll"     <<<<<<<<<
 Volume in drive C is win10
 Volume Serial Number is ABCD-E012

 Directory of C:\ProgramData\anaconda3

16/12/2023  02:08         6,000,640 python311.dll
               1 File(s)      6,000,640 bytes
               0 Dir(s)  54,514,569,216 bytes free


(base) C:\Windows\system32>dir "C:/ProgramData/anaconda3/python311.dll"     <<<<<<<<<
 Volume in drive C is win10
 Volume Serial Number is ABCD-E012

 Directory of C:\ProgramData\anaconda3

File Not Found


(base) C:\Windows\system32>dir "C:/ProgramData/anaconda3/" | findstr "python311.dll"     <<<<<<<<<
16/12/2023  02:08         6,000,640 python311.dll


```

**Comment by mrkn** [comment]
@felixonmars I don't have Windows environment so I cannot investigate your problem right now. But, Conda's Python can be used with PyCall on Windows as is according to [this CI result](https://github.com/mrkn/pycall.rb/actions/runs/11452084234/job/31862363481).

**Comment by felixonmars** [comment]
I guess you meant to mention @felixmarch instead of me :P

**Comment by mrkn** [comment]
@felixonmars Oh no! I'm sorry for mentioning you by mistake.
